title: Rubin Future
description: Community planning for the future of Rubin Observatory after LSST
url: "https://rubin-observatory.github.io"
baseurl: "/Rubin2036"

markdown: kramdown
permalink: pretty

navigation:
  - title: Home
    url: /
  - title: Meetings
    url: /meetings/
  - title: Documents
    url: /documents/
  - title: Community
    url: /community/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

exclude:
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
